<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_uname</name>
   <tag></tag>
   <elementGuidId>2ba7d0e6-01a9-4b65-9c6c-6ff60de7e0d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Username:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>184e3ea7-f03c-48c8-854e-a3e29fb08421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3910565f-5bd5-4be8-a47c-293628d4742a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uname</value>
      <webElementGuid>1617b334-69bf-47dd-904a-64376e6c74e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>d9151769-e0e1-4ed4-bee5-e37c43457663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uname</value>
      <webElementGuid>5052ce9e-0c25-4422-92dd-295afa0e6516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uname&quot;)</value>
      <webElementGuid>d4e27729-431a-4a55-bc52-7f01adffe4d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uname']</value>
      <webElementGuid>67486bf1-296b-4b4f-83d5-42f9595ae8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0609a4a6-92ea-40a5-874f-c957ba64b61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'uname' and @placeholder = 'test' and @name = 'uname']</value>
      <webElementGuid>0250788b-6c64-4547-aec6-691d6ea576d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
